type: docker
kind: pipeline
name: default


steps:
  - name: test
    privileged: true
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker ps -a

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock